# Generated by Django 2.2.7 on 2019-11-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phoneNumber',
            field=models.BigIntegerField(default=912345678, max_length=15),
        ),
    ]
