# Generated by Django 2.2.7 on 2019-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191123_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile-pics'),
        ),
    ]
