# Generated by Django 2.2.7 on 2019-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191125_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
    ]
